# Form implementation generated from reading ui file 'D:\K24406H\PROJECT\ui\customer_management\customer_management.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_CustomerManagement(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 800)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1000, 900))
        self.label.setStyleSheet("background-color: rgb(120, 99, 84);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 40, 721, 681))
        font = QtGui.QFont()
        font.setFamily("Perpetua")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel {\n"
"    background-color: #C4B8AE;\n"
"    color: white;\n"
"    padding: 5px;\n"
"    border-radius: 8px;\n"
"}\n"
"")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(100, 90, 311, 361))
        font = QtGui.QFont()
        font.setFamily("Perpetua Titling MT")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("QGroupBox {\n"
"    background-color: #D6C8BE; /* Màu nền hợp với #C4B8AE */\n"
"    border: 2px solid #8D735F; /* Viền màu tối hơn để tạo điểm nhấn */\n"
"    border-radius: 12px; /* Bo góc */\n"
"    padding: 10px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top center; /* Canh giữa tiêu đề */\n"
"    padding: 5px;\n"
"    background-color: #C4B8AE; /* Nền tiêu đề tiệp màu với label */\n"
"    border-radius: 6px;\n"
"}\n"
"")
        self.groupBox.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.lineEditFullName = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEditFullName.setGeometry(QtCore.QRect(130, 70, 151, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditFullName.sizePolicy().hasHeightForWidth())
        self.lineEditFullName.setSizePolicy(sizePolicy)
        self.lineEditFullName.setStyleSheet("QLineEdit {\n"
"    background-color: #f5f0eb;  /* Màu be nhạt, hợp với theme tổng thể */\n"
"    border: 2px solid #a08975;  /* Viền màu nâu nhạt */\n"
"    border-radius: 8px;  /* Bo góc */\n"
"    padding: 4px;  /* Thêm khoảng cách bên trong */\n"
"    color: #4a3b2e;  /* Chữ màu nâu đậm cho dễ đọc */\n"
"    font-size: 14px;  \n"
"}\n"
"")
        self.lineEditFullName.setObjectName("lineEditFullName")
        self.lineEditPhone = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEditPhone.setGeometry(QtCore.QRect(130, 120, 151, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditPhone.sizePolicy().hasHeightForWidth())
        self.lineEditPhone.setSizePolicy(sizePolicy)
        self.lineEditPhone.setStyleSheet("QLineEdit {\n"
"    background-color: #f5f0eb;  /* Màu be nhạt, hợp với theme tổng thể */\n"
"    border: 2px solid #a08975;  /* Viền màu nâu nhạt */\n"
"    border-radius: 8px;  /* Bo góc */\n"
"    padding: 4px;  /* Thêm khoảng cách bên trong */\n"
"    color: #4a3b2e;  /* Chữ màu nâu đậm cho dễ đọc */\n"
"    font-size: 14px;  \n"
"}\n"
"")
        self.lineEditPhone.setObjectName("lineEditPhone")
        self.lineEdit_3 = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEdit_3.setGeometry(QtCore.QRect(130, 170, 151, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_3.sizePolicy().hasHeightForWidth())
        self.lineEdit_3.setSizePolicy(sizePolicy)
        self.lineEdit_3.setStyleSheet("QLineEdit {\n"
"    background-color: #f5f0eb;  /* Màu be nhạt, hợp với theme tổng thể */\n"
"    border: 2px solid #a08975;  /* Viền màu nâu nhạt */\n"
"    border-radius: 8px;  /* Bo góc */\n"
"    padding: 4px;  /* Thêm khoảng cách bên trong */\n"
"    color: #4a3b2e;  /* Chữ màu nâu đậm cho dễ đọc */\n"
"    font-size: 14px;  \n"
"}\n"
"")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEdit_4.setGeometry(QtCore.QRect(130, 280, 151, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_4.sizePolicy().hasHeightForWidth())
        self.lineEdit_4.setSizePolicy(sizePolicy)
        self.lineEdit_4.setStyleSheet("QLineEdit {\n"
"    background-color: #f5f0eb;  /* Màu be nhạt, hợp với theme tổng thể */\n"
"    border: 2px solid #a08975;  /* Viền màu nâu nhạt */\n"
"    border-radius: 8px;  /* Bo góc */\n"
"    padding: 4px;  /* Thêm khoảng cách bên trong */\n"
"    color: #4a3b2e;  /* Chữ màu nâu đậm cho dễ đọc */\n"
"    font-size: 14px;  \n"
"}\n"
"")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_8 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(10, 60, 101, 41))
        self.label_8.setStyleSheet("QLabel {\n"
"    background-color: #e1d6cc;  /* Màu nền be nhẹ hợp với tổng thể */\n"
"    border-radius: 10px;  /* Bo góc mềm mại */\n"
"    padding: 6px 10px;  /* Thêm khoảng cách để nhìn đẹp hơn */\n"
"    color: #4a3b2e;  /* Chữ màu nâu đậm cho dễ đọc */\n"
"    font-weight: bold;  /* Làm chữ rõ ràng hơn */\n"
"}\n"
"")
        self.label_8.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_8.setWordWrap(True)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(10, 110, 101, 41))
        self.label_9.setStyleSheet("QLabel {\n"
"    background-color: #e1d6cc;  /* Màu nền be nhẹ hợp với tổng thể */\n"
"    border-radius: 10px;  /* Bo góc mềm mại */\n"
"    padding: 6px 10px;  /* Thêm khoảng cách để nhìn đẹp hơn */\n"
"    color: #4a3b2e;  /* Chữ màu nâu đậm cho dễ đọc */\n"
"    font-weight: bold;  /* Làm chữ rõ ràng hơn */\n"
"}\n"
"")
        self.label_9.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_9.setWordWrap(True)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_10.setGeometry(QtCore.QRect(10, 160, 101, 41))
        self.label_10.setStyleSheet("QLabel {\n"
"    background-color: #e1d6cc;  /* Màu nền be nhẹ hợp với tổng thể */\n"
"    border-radius: 10px;  /* Bo góc mềm mại */\n"
"    padding: 6px 10px;  /* Thêm khoảng cách để nhìn đẹp hơn */\n"
"    color: #4a3b2e;  /* Chữ màu nâu đậm cho dễ đọc */\n"
"    font-weight: bold;  /* Làm chữ rõ ràng hơn */\n"
"}\n"
"")
        self.label_10.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_10.setWordWrap(True)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_11.setGeometry(QtCore.QRect(10, 270, 101, 51))
        self.label_11.setStyleSheet("QLabel {\n"
"    background-color: #e1d6cc;  /* Màu nền be nhẹ hợp với tổng thể */\n"
"    border-radius: 10px;  /* Bo góc mềm mại */\n"
"    padding: 6px 10px;  /* Thêm khoảng cách để nhìn đẹp hơn */\n"
"    color: #4a3b2e;  /* Chữ màu nâu đậm cho dễ đọc */\n"
"    font-weight: bold;  /* Làm chữ rõ ràng hơn */\n"
"}\n"
"")
        self.label_11.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_11.setWordWrap(True)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_12.setGeometry(QtCore.QRect(10, 210, 101, 51))
        self.label_12.setStyleSheet("QLabel {\n"
"    background-color: #e1d6cc;  /* Màu nền be nhẹ hợp với tổng thể */\n"
"    border-radius: 10px;  /* Bo góc mềm mại */\n"
"    padding: 6px 10px;  /* Thêm khoảng cách để nhìn đẹp hơn */\n"
"    color: #4a3b2e;  /* Chữ màu nâu đậm cho dễ đọc */\n"
"    font-weight: bold;  /* Làm chữ rõ ràng hơn */\n"
"}\n"
"")
        self.label_12.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_12.setWordWrap(True)
        self.label_12.setObjectName("label_12")
        self.lineEdit_6 = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEdit_6.setGeometry(QtCore.QRect(130, 220, 151, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_6.sizePolicy().hasHeightForWidth())
        self.lineEdit_6.setSizePolicy(sizePolicy)
        self.lineEdit_6.setStyleSheet("QLineEdit {\n"
"    background-color: #f5f0eb;  /* Màu be nhạt, hợp với theme tổng thể */\n"
"    border: 2px solid #a08975;  /* Viền màu nâu nhạt */\n"
"    border-radius: 8px;  /* Bo góc */\n"
"    padding: 4px;  /* Thêm khoảng cách bên trong */\n"
"    color: #4a3b2e;  /* Chữ màu nâu đậm cho dễ đọc */\n"
"    font-size: 14px;  \n"
"}\n"
"")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(80, 510, 351, 171))
        font = QtGui.QFont()
        font.setFamily("Perpetua Titling MT")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setStyleSheet("QGroupBox {\n"
"    background-color: #D6C8BE; /* Màu nền hợp với #C4B8AE */\n"
"    border: 2px solid #8D735F; /* Viền màu tối hơn để tạo điểm nhấn */\n"
"    border-radius: 12px; /* Bo góc */\n"
"    padding: 10px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top center; /* Canh giữa tiêu đề */\n"
"    padding: 5px;\n"
"    background-color: #C4B8AE; /* Nền tiêu đề tiệp màu với label */\n"
"    border-radius: 6px;\n"
"}\n"
"")
        self.groupBox_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_7 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(10, 20, 81, 131))
        self.label_7.setStyleSheet("QLabel {\n"
"    background-color: #e1d6cc;  /* Màu nền be nhẹ hợp với tổng thể */\n"
"    border-radius: 10px;  /* Bo góc mềm mại */\n"
"    padding: 6px 10px;  /* Thêm khoảng cách để nhìn đẹp hơn */\n"
"    color: #4a3b2e;  /* Chữ màu nâu đậm cho dễ đọc */\n"
"    font-weight: bold;  /* Làm chữ rõ ràng hơn */\n"
"}\n"
"")
        self.label_7.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName("label_7")
        self.lineEditSearchPhone = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.lineEditSearchPhone.setGeometry(QtCore.QRect(110, 50, 221, 41))
        self.lineEditSearchPhone.setStyleSheet("QLineEdit {\n"
"    background-color: #e1d6cc;  /* Màu nền giống label */\n"
"    border: 2px solid #c1a78e;  /* Viền nâu nhạt tạo điểm nhấn */\n"
"    border-radius: 10px;  /* Bo góc mềm mại */\n"
"    padding: 6px 10px;  /* Thêm khoảng trống để nhập dễ hơn */\n"
"    color: #4a3b2e;  /* Chữ nâu đậm, dễ đọc */\n"
"    font-size: 14px;  /* Chỉnh cỡ chữ để nhìn đẹp hơn */\n"
"    selection-background-color: #b79d8b;  /* Màu khi bôi đen chữ */\n"
"}\n"
"")
        self.lineEditSearchPhone.setObjectName("lineEditSearchPhone")
        self.pushButtonSearch = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.pushButtonSearch.setGeometry(QtCore.QRect(130, 110, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Perpetua Titling MT")
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonSearch.setFont(font)
        self.pushButtonSearch.setStyleSheet("QPushButton {\n"
"    background-color: #A48C74; /* Màu hợp với tông màu tổng thể */\n"
"    color: white; /* Chữ màu trắng để dễ nhìn */\n"
"    border-radius: 10px; /* Bo góc */\n"
"    padding: 5px 10px; /* Canh lề cho đẹp */\n"
"    border: 2px solid #8B6F55; /* Viền đậm hơn một chút */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #8B6F55; /* Đổi màu khi hover để có hiệu ứng */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #786354; /* Khi nhấn thì màu đậm hơn */\n"
"}\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:\\K24406H\\PROJECT\\ui\\customer_management\\../images/image(6).png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonSearch.setIcon(icon)
        self.pushButtonSearch.setObjectName("pushButtonSearch")
        self.groupBox_4 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(540, 500, 181, 191))
        font = QtGui.QFont()
        font.setFamily("Perpetua Titling MT")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setStyleSheet("QGroupBox {\n"
"    background-color: #D6C8BE; /* Màu nền hợp với #C4B8AE */\n"
"    border: 2px solid #8D735F; /* Viền màu tối hơn để tạo điểm nhấn */\n"
"    border-radius: 12px; /* Bo góc */\n"
"    padding: 10px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top center; /* Canh giữa tiêu đề */\n"
"    padding: 5px;\n"
"    background-color: #C4B8AE; /* Nền tiêu đề tiệp màu với label */\n"
"    border-radius: 6px;\n"
"}\n"
"")
        self.groupBox_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.groupBox_4.setObjectName("groupBox_4")
        self.pushButtonEdit = QtWidgets.QPushButton(parent=self.groupBox_4)
        self.pushButtonEdit.setGeometry(QtCore.QRect(30, 40, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Perpetua Titling MT")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonEdit.setFont(font)
        self.pushButtonEdit.setStyleSheet("QPushButton {\n"
"    background-color: #A48C74; /* Màu hợp với tông màu tổng thể */\n"
"    color: white; /* Chữ màu trắng để dễ nhìn */\n"
"    border-radius: 10px; /* Bo góc */\n"
"    padding: 5px 10px; /* Canh lề cho đẹp */\n"
"    border: 2px solid #8B6F55; /* Viền đậm hơn một chút */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #8B6F55; /* Đổi màu khi hover để có hiệu ứng */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #786354; /* Khi nhấn thì màu đậm hơn */\n"
"}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("D:\\K24406H\\PROJECT\\ui\\customer_management\\../images/image(8).png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonEdit.setIcon(icon1)
        self.pushButtonEdit.setObjectName("pushButtonEdit")
        self.pushButtonRemove = QtWidgets.QPushButton(parent=self.groupBox_4)
        self.pushButtonRemove.setGeometry(QtCore.QRect(30, 90, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Perpetua Titling MT")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonRemove.setFont(font)
        self.pushButtonRemove.setStyleSheet("QPushButton {\n"
"    background-color: #A48C74; /* Màu hợp với tông màu tổng thể */\n"
"    color: white; /* Chữ màu trắng để dễ nhìn */\n"
"    border-radius: 10px; /* Bo góc */\n"
"    padding: 5px 10px; /* Canh lề cho đẹp */\n"
"    border: 2px solid #8B6F55; /* Viền đậm hơn một chút */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #8B6F55; /* Đổi màu khi hover để có hiệu ứng */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #786354; /* Khi nhấn thì màu đậm hơn */\n"
"}\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("D:\\K24406H\\PROJECT\\ui\\customer_management\\../images/image(7).png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonRemove.setIcon(icon2)
        self.pushButtonRemove.setObjectName("pushButtonRemove")
        self.pushButtonAdd = QtWidgets.QPushButton(parent=self.groupBox_4)
        self.pushButtonAdd.setGeometry(QtCore.QRect(30, 140, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Perpetua Titling MT")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonAdd.setFont(font)
        self.pushButtonAdd.setStyleSheet("QPushButton {\n"
"    background-color: #A48C74; /* Màu hợp với tông màu tổng thể */\n"
"    color: white; /* Chữ màu trắng để dễ nhìn */\n"
"    border-radius: 10px; /* Bo góc */\n"
"    padding: 5px 10px; /* Canh lề cho đẹp */\n"
"    border: 2px solid #8B6F55; /* Viền đậm hơn một chút */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #8B6F55; /* Đổi màu khi hover để có hiệu ứng */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #786354; /* Khi nhấn thì màu đậm hơn */\n"
"}\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("D:\\K24406H\\PROJECT\\ui\\customer_management\\../images/image(5).png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonAdd.setIcon(icon3)
        self.pushButtonAdd.setObjectName("pushButtonAdd")
        self.groupBox_3 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(460, 110, 271, 321))
        font = QtGui.QFont()
        font.setFamily("Perpetua Titling MT")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setStyleSheet("QGroupBox {\n"
"    background-color: #D6C8BE; /* Màu nền hợp với #C4B8AE */\n"
"    border: 2px solid #8D735F; /* Viền màu tối hơn để tạo điểm nhấn */\n"
"    border-radius: 12px; /* Bo góc */\n"
"    padding: 10px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top center; /* Canh giữa tiêu đề */\n"
"    padding: 5px;\n"
"    background-color: #C4B8AE; /* Nền tiêu đề tiệp màu với label */\n"
"    border-radius: 6px;\n"
"}\n"
"")
        self.groupBox_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.groupBox_3.setObjectName("groupBox_3")
        self.listWidgetCustomers = QtWidgets.QListWidget(parent=self.groupBox_3)
        self.listWidgetCustomers.setGeometry(QtCore.QRect(5, 40, 261, 271))
        self.listWidgetCustomers.setStyleSheet("background-color: rgb(170, 139, 114);")
        self.listWidgetCustomers.setObjectName("listWidgetCustomers")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "GUEST DETAILS:"))
        self.label_8.setText(_translate("MainWindow", "FULL NAME:"))
        self.label_9.setText(_translate("MainWindow", "PHONE NUMBER:"))
        self.label_10.setText(_translate("MainWindow", "ARRIVAL:"))
        self.label_11.setText(_translate("MainWindow", "ROOM NUMBER:"))
        self.label_12.setText(_translate("MainWindow", "DEPARTURE:"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Search:"))
        self.label_7.setText(_translate("MainWindow", "Search by phone number:"))
        self.pushButtonSearch.setText(_translate("MainWindow", "Search"))
        self.groupBox_4.setTitle(_translate("MainWindow", "ACTION:"))
        self.pushButtonEdit.setText(_translate("MainWindow", "Edit"))
        self.pushButtonRemove.setText(_translate("MainWindow", "Remove"))
        self.pushButtonAdd.setText(_translate("MainWindow", "ADD"))
        self.groupBox_3.setTitle(_translate("MainWindow", "GUEST DETAILS:"))
