# Form implementation generated from reading ui file 'D:\K24406H\PROJECT\ui\room_management\room_management.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_RoomManagement(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(575, 575)
        font = QtGui.QFont()
        font.setFamily("Sitka Banner Semibold")
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color: rgb(123, 117, 107);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.listWidgetRoomList = QtWidgets.QListWidget(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Sitka")
        self.listWidgetRoomList.setFont(font)
        self.listWidgetRoomList.setStyleSheet("QListWidget {\n"
"    border: 2px solid #493d37;\n"
"    border-radius: 5px;\n"
"    background-color: #e8e7e6;\n"
"    color: #44413b;\n"
"}\n"
"\n"
"QListWidget::item {\n"
"    padding: 5px;\n"
"    border: 1px solid transparent;\n"
"}\n"
"\n"
"QListWidget::item:hover {\n"
"    /* Hiệu ứng khi di chuột qua mục */\n"
"    background-color: #f1f1f1;\n"
"    border: 1px solid #493d37;\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QListWidget::item:selected {\n"
"    background-color: #b8b4ad;\n"
"    color: #ffffff;\n"
"    border: 1px solid #b8b4ad;\n"
"}\n"
"")
        self.listWidgetRoomList.setObjectName("listWidgetRoomList")
        item = QtWidgets.QListWidgetItem()
        self.listWidgetRoomList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidgetRoomList.addItem(item)
        self.gridLayout_2.addWidget(self.listWidgetRoomList, 5, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.radioButtonAvailable = QtWidgets.QRadioButton(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Sitka Subheading")
        font.setPointSize(9)
        self.radioButtonAvailable.setFont(font)
        self.radioButtonAvailable.setStyleSheet("QRadioButton {\n"
"    transition: all 0.3s ease;\n"
"    color: #e8e7e6\n"
"}\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:\\K24406H\\PROJECT\\ui\\room_management\\../images/image(15).png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.radioButtonAvailable.setIcon(icon)
        self.radioButtonAvailable.setObjectName("radioButtonAvailable")
        self.gridLayout.addWidget(self.radioButtonAvailable, 3, 1, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Sitka Text Semibold")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel {\n"
"    color: #e8e7e6\n"
"}")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Sitka Text Semibold")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("QLabel {\n"
"    color: #e8e7e6\n"
"}")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Sitka Text Semibold")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel {\n"
"    color: #e8e7e6\n"
"}")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.radioButtonUnavailable = QtWidgets.QRadioButton(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Sitka Heading")
        font.setPointSize(9)
        self.radioButtonUnavailable.setFont(font)
        self.radioButtonUnavailable.setStyleSheet("QRadioButton {\n"
"    transition: all 0.3s ease;\n"
"    color: #e8e7e6\n"
"}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("D:\\K24406H\\PROJECT\\ui\\room_management\\../images/image(14).png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.radioButtonUnavailable.setIcon(icon1)
        self.radioButtonUnavailable.setObjectName("radioButtonUnavailable")
        self.gridLayout.addWidget(self.radioButtonUnavailable, 3, 2, 1, 1)
        self.comboBoxRoomNumber = QtWidgets.QComboBox(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(9)
        self.comboBoxRoomNumber.setFont(font)
        self.comboBoxRoomNumber.setStyleSheet("QComboBox {\n"
"    border: 2px solid #6d685f;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    background-color: #ffffff;\n"
"    color: #000000;\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    border: 3px solid #b8b4ad;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #f9f9f9;\n"
"    selection-background-color: #c4c0bb;\n"
"    selection-color: #37342f;      \n"
"}")
        self.comboBoxRoomNumber.setObjectName("comboBoxRoomNumber")
        self.comboBoxRoomNumber.addItem("")
        self.comboBoxRoomNumber.addItem("")
        self.comboBoxRoomNumber.addItem("")
        self.comboBoxRoomNumber.addItem("")
        self.comboBoxRoomNumber.addItem("")
        self.comboBoxRoomNumber.addItem("")
        self.comboBoxRoomNumber.addItem("")
        self.comboBoxRoomNumber.addItem("")
        self.gridLayout.addWidget(self.comboBoxRoomNumber, 2, 1, 1, 2)
        self.comboBoxFloor = QtWidgets.QComboBox(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(9)
        self.comboBoxFloor.setFont(font)
        self.comboBoxFloor.setStyleSheet("QComboBox {\n"
"    border: 2px solid #6d685f;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    background-color: #ffffff;\n"
"    color: #000000;\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    border: 3px solid #b8b4ad;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #f9f9f9;\n"
"    selection-background-color: #c4c0bb;\n"
"    selection-color: #37342f;      \n"
"}")
        self.comboBoxFloor.setObjectName("comboBoxFloor")
        self.comboBoxFloor.addItem("")
        self.comboBoxFloor.addItem("")
        self.comboBoxFloor.addItem("")
        self.comboBoxFloor.addItem("")
        self.comboBoxFloor.addItem("")
        self.comboBoxFloor.addItem("")
        self.comboBoxFloor.addItem("")
        self.comboBoxFloor.addItem("")
        self.comboBoxFloor.addItem("")
        self.comboBoxFloor.addItem("")
        self.gridLayout.addWidget(self.comboBoxFloor, 1, 1, 1, 2)
        self.comboBoxRoomType = QtWidgets.QComboBox(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(9)
        self.comboBoxRoomType.setFont(font)
        self.comboBoxRoomType.setStyleSheet("QComboBox {\n"
"    border: 2px solid #6d685f;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    background-color: #ffffff;\n"
"    color: #000000;\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    border: 3px solid #b8b4ad;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #f9f9f9;\n"
"    selection-background-color: #c4c0bb;\n"
"    selection-color: #37342f;      \n"
"}")
        self.comboBoxRoomType.setObjectName("comboBoxRoomType")
        self.comboBoxRoomType.addItem("")
        self.comboBoxRoomType.addItem("")
        self.comboBoxRoomType.addItem("")
        self.comboBoxRoomType.addItem("")
        self.gridLayout.addWidget(self.comboBoxRoomType, 0, 1, 1, 2)
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Sitka Text Semibold")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("QLabel {\n"
"    color: #e8e7e6\n"
"}")
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButtonUpdate = QtWidgets.QPushButton(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.pushButtonUpdate.setFont(font)
        self.pushButtonUpdate.setStyleSheet("QPushButton {\n"
"    background-color: #e8e7e6;\n"
"    color: #44413b; \n"
"    border: none;\n"
"    border-radius: 8px; \n"
"    padding: 5px 20px; \n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #c2c0bd;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #918d88; \n"
"}")
        self.pushButtonUpdate.setObjectName("pushButtonUpdate")
        self.horizontalLayout_2.addWidget(self.pushButtonUpdate)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 575, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Rooms Management Screen"))
        __sortingEnabled = self.listWidgetRoomList.isSortingEnabled()
        self.listWidgetRoomList.setSortingEnabled(False)
        item = self.listWidgetRoomList.item(0)
        item.setText(_translate("MainWindow", "Classic"))
        item = self.listWidgetRoomList.item(1)
        item.setText(_translate("MainWindow", "Deluxe"))
        self.listWidgetRoomList.setSortingEnabled(__sortingEnabled)
        self.radioButtonAvailable.setText(_translate("MainWindow", "Available"))
        self.label.setText(_translate("MainWindow", "Room type:"))
        self.label_3.setText(_translate("MainWindow", "Room number:"))
        self.label_2.setText(_translate("MainWindow", "Floor:"))
        self.radioButtonUnavailable.setText(_translate("MainWindow", "Unavailable"))
        self.comboBoxRoomNumber.setItemText(0, _translate("MainWindow", "01"))
        self.comboBoxRoomNumber.setItemText(1, _translate("MainWindow", "02"))
        self.comboBoxRoomNumber.setItemText(2, _translate("MainWindow", "03"))
        self.comboBoxRoomNumber.setItemText(3, _translate("MainWindow", "04"))
        self.comboBoxRoomNumber.setItemText(4, _translate("MainWindow", "05"))
        self.comboBoxRoomNumber.setItemText(5, _translate("MainWindow", "06"))
        self.comboBoxRoomNumber.setItemText(6, _translate("MainWindow", "07"))
        self.comboBoxRoomNumber.setItemText(7, _translate("MainWindow", "08"))
        self.comboBoxFloor.setItemText(0, _translate("MainWindow", "1"))
        self.comboBoxFloor.setItemText(1, _translate("MainWindow", "2"))
        self.comboBoxFloor.setItemText(2, _translate("MainWindow", "3"))
        self.comboBoxFloor.setItemText(3, _translate("MainWindow", "4"))
        self.comboBoxFloor.setItemText(4, _translate("MainWindow", "5"))
        self.comboBoxFloor.setItemText(5, _translate("MainWindow", "6"))
        self.comboBoxFloor.setItemText(6, _translate("MainWindow", "7"))
        self.comboBoxFloor.setItemText(7, _translate("MainWindow", "8"))
        self.comboBoxFloor.setItemText(8, _translate("MainWindow", "9"))
        self.comboBoxFloor.setItemText(9, _translate("MainWindow", "10"))
        self.comboBoxRoomType.setItemText(0, _translate("MainWindow", "Classic room"))
        self.comboBoxRoomType.setItemText(1, _translate("MainWindow", "Deluxe room"))
        self.comboBoxRoomType.setItemText(2, _translate("MainWindow", "Family room"))
        self.comboBoxRoomType.setItemText(3, _translate("MainWindow", "Master suite"))
        self.label_4.setText(_translate("MainWindow", "Status:"))
        self.pushButtonUpdate.setText(_translate("MainWindow", "Update"))
        self.pushButtonUpdate.setShortcut(_translate("MainWindow", "Return"))
