# Form implementation generated from reading ui file 'D:\K24406H\PROJECT\ui\login_screen\login_screen.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(571, 443)
        font = QtGui.QFont()
        font.setFamily("MS PMincho")
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color: rgb(123, 117, 107);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButtonSignIn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonSignIn.setGeometry(QtCore.QRect(220, 350, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.pushButtonSignIn.setFont(font)
        self.pushButtonSignIn.setStyleSheet("QPushButton {\n"
"    background-color: #e8e7e6;\n"
"    color: #737373; \n"
"    border: none;\n"
"    border-radius: 8px; \n"
"    padding: 5px 20px; \n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #c2c0bd;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #918d88; \n"
"}\n"
"")
        self.pushButtonSignIn.setObjectName("pushButtonSignIn")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(120, 50, 321, 281))
        font = QtGui.QFont()
        font.setFamily("Sitka Small Semibold")
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("QGroupBox {\n"
"    background-color: #e8e7e6;\n"
"    border: 2px solid #493d37; \n"
"    border-radius: 15px;\n"
"     margin-top: 5px;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: border; \n"
"    subcontrol-position: top center;\n"
"    background-color: #493d37;\n"
"    color: white;\n"
"    padding: 5px 10px; \n"
"    border-radius: 5px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lineEditPassWord = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEditPassWord.setStyleSheet("QLineEdit {\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 20px;\n"
"    padding: 10px 15px;\n"
"    font-size: 14px;\n"
"    background-color: #f0f0f0;\n"
"    box-shadow: 2px 2px 5px rgba(0, 0, 0, 0.1);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 1px solid  #262626;\n"
"    background-color: #ffffff;\n"
"    box-shadow: 0 0 5px rgba(98, 0, 238, 0.5); \n"
"}")
        self.lineEditPassWord.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEditPassWord.setObjectName("lineEditPassWord")
        self.gridLayout_2.addWidget(self.lineEditPassWord, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Sitka Text Semibold")
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel {\n"
"    background: transparent;\n"
"    color: #737373;\n"
"    margin-top: 20\n"
"}")
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.radioButtonRooms = QtWidgets.QRadioButton(parent=self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Sitka Text Semibold")
        self.radioButtonRooms.setFont(font)
        self.radioButtonRooms.setStyleSheet("QRadioButton {\n"
"    background-color: rgb(232, 231, 230);\n"
"    transition: all 0.3s ease;\n"
"}\n"
"")
        self.radioButtonRooms.setObjectName("radioButtonRooms")
        self.gridLayout_2.addWidget(self.radioButtonRooms, 3, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Sitka Text Semibold")
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("QLabel {\n"
"    background: transparent;\n"
"    color: #737373\n"
"}")
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.radioButtonCustomers = QtWidgets.QRadioButton(parent=self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Sitka Text Semibold")
        self.radioButtonCustomers.setFont(font)
        self.radioButtonCustomers.setStyleSheet("QRadioButton {\n"
"    background-color: rgb(232, 231, 230);\n"
"    transition: all 0.3s ease;\n"
"}")
        self.radioButtonCustomers.setObjectName("radioButtonCustomers")
        self.gridLayout_2.addWidget(self.radioButtonCustomers, 4, 1, 1, 1)
        self.lineEditUserName = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEditUserName.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.IBeamCursor))
        self.lineEditUserName.setStyleSheet("QLineEdit {\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 20px;\n"
"    padding: 10px 15px;\n"
"    font-size: 14px;\n"
"    background-color: #f0f0f0;\n"
"    box-shadow: 2px 2px 5px rgba(0, 0, 0, 0.1);\n"
"    margin-top: 20\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 1px solid  #262626;\n"
"    background-color: #ffffff;\n"
"    box-shadow: 0 0 5px rgba(98, 0, 238, 0.5); \n"
"}")
        self.lineEditUserName.setFrame(True)
        self.lineEditUserName.setObjectName("lineEditUserName")
        self.gridLayout_2.addWidget(self.lineEditUserName, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-70, 20, 736, 471))
        self.label.setStyleSheet("")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("D:\\K24406H\\PROJECT\\ui\\login_screen\\../images/image(9).jpeg"))
        self.label.setScaledContents(False)
        self.label.setObjectName("label")
        self.label.raise_()
        self.pushButtonSignIn.raise_()
        self.groupBox.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 571, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Login_screen"))
        self.pushButtonSignIn.setText(_translate("MainWindow", "Sign in"))
        self.groupBox.setTitle(_translate("MainWindow", "Login:"))
        self.label_2.setText(_translate("MainWindow", "Username:"))
        self.radioButtonRooms.setText(_translate("MainWindow", "Rooms management"))
        self.label_3.setText(_translate("MainWindow", "Password:"))
        self.radioButtonCustomers.setText(_translate("MainWindow", "Customers management"))
